pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'Building Service B..'
      }
    }
    stage('Test') {
      parallel {
        stage('Test') {
          steps {
            echo 'Testing..'
          }
        }
        stage('Integration') {
          steps {
            echo 'Hello Eden'
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }
}
